### ISSUE TITLE
How to turn off scaling up and down in canvas.

### ISSUE THREAD

**Issue by mashish584** [netless-io/react-native-fastboard#1]
Hi,

I've integrated Fastboard & it's working fine as expected. But I don't want user to zoomIn or zoomOut in view I want canvas to be same as device width and height. 

For web, I was able to do the same using below snippet with white-react-sdk

```
const cameraBound = {
      // Zoom settings
      maxContentMode: contentModeScale(1),
      minContentMode: contentModeScale(1),
 };
```

I've tried below config in RN but it's not working for me.

```
  React.useEffect(() => {
    (async () => {
      const response = await getAgoraRoomDetails();
      const roomParams: RoomConfig = {
        uuid: response.roomUUID,
        uid: Platform.OS === 'ios' ? 'ashish00123' : 'ashish00584',
        roomToken: response.roomToken,
        region: 'in-mum',
        cameraBound: {
          maxContentMode: {
            mode: 'Scale',
            scale: 1,
          },
          minContentMode: {
            mode: 'Scale',
            scale: 1,
          },
        },
      };
      setRoomParams(roomParams);
    })();
  }, []);
```

```
   {roomParams !== null && (
        <FastRoom
          sdkParams={sdkParams}
          roomParams={roomParams}
          style={
            usingCustomDesign
              ? {
                  container: styles.fastRoomContainer,
                  controlBar: customStyles.controlBar,
                  horizontalControlBar: customStyles.horizontalControlBar,
                  subPanel: customStyles.subPanel,
                  compactPanel: customStyles.compactPanel,
                  applianceSelectedColor: '#ff3838',
                  regularPanel: customStyles.regularPanel,
                }
              : {
                  container: styles.fastRoomContainer,
                }
          }
          joinRoomSuccessCallback={room => {
            fastRoomObj = room;
          }}
          roomCallback={roomCallback}
        />
      )}
```

Thanks

**Comment by mashish584** [comment]
@vince-hz, can you please take a look at the comment above?

**Comment by vince-hz** [comment]
You can try set `disableCameraTransform` to `true`
```
const roomParams: RoomConfig = {
    ****
    disableCameraTransform: true,
}
```
@mashish584

**Comment by mashish584** [comment]
https://github.com/netless-io/react-native-fastboard/assets/33250693/bee167a6-ec1d-4178-bc92-8b5ac93b87b1


@vince-hz Thanks for the response.
I tried disableCameraTransform as true still able to zoom in or out.

**Comment by vince-hz** [comment]
Maybe there are some bugs with white-web-sdk. Please try execute the code below after you join room success:
```
room.disableCameraTransform = true;
```
@mashish584

**Comment by mashish584** [comment]
Hi @vince-hz 

Tried mentioned snipped in joinRoomSuccess callback still able to zoom in or out.

```
 const onJoinRoomSuccess = useCallback((room: FastRoomObject | undefined) => {
    if (room) {
      fastRoomObj.current = room;
      room.disableCameraTransform = true;
    }
  }, []);
```

**Comment by vince-hz** [comment]
My computer has not been able to start react-native since I upgraded it, and after checking I realized that `disableCameraTransform` is an instance method of WhiteRoom. So the way it should be called in Fastboard is like this: 

```
room.room.disableCameraTransform(true);
```

Also our whiteboard is actually running in a WebView, so you should be able to open a Chrome or Safari debugger to debug it. Our react-native-whiteboard or react-native-fastboard mainly does some call wrapping.

Here is a web api reference. Hope may help you.
https://api-ref.agora.io/en/interactive-whiteboard-sdk/web/2.x/index.html

@mashish584

**Comment by mashish584** [comment]
Thanks, @vince-hz for all the help.

I'll check this on my end. For now I'm closing this issue. Will reopen if issue persist.
